//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPT.WebAPI.Tests.WebServiceClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/CPT.WebAPI.Contract.Data")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AllergenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NutritionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CPT.WebAPI.Tests.WebServiceClient.Manufacturer ProductManufacturerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Allergen {
            get {
                return this.AllergenField;
            }
            set {
                if ((object.ReferenceEquals(this.AllergenField, value) != true)) {
                    this.AllergenField = value;
                    this.RaisePropertyChanged("Allergen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nutrition {
            get {
                return this.NutritionField;
            }
            set {
                if ((object.ReferenceEquals(this.NutritionField, value) != true)) {
                    this.NutritionField = value;
                    this.RaisePropertyChanged("Nutrition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIDField, value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CPT.WebAPI.Tests.WebServiceClient.Manufacturer ProductManufacturer {
            get {
                return this.ProductManufacturerField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductManufacturerField, value) != true)) {
                    this.ProductManufacturerField = value;
                    this.RaisePropertyChanged("ProductManufacturer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Manufacturer", Namespace="http://schemas.datacontract.org/2004/07/CPT.WebAPI.Contract.Data")]
    [System.SerializableAttribute()]
    public partial class Manufacturer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LongtitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ManufacturerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longtitude {
            get {
                return this.LongtitudeField;
            }
            set {
                if ((this.LongtitudeField.Equals(value) != true)) {
                    this.LongtitudeField = value;
                    this.RaisePropertyChanged("Longtitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ManufacturerID {
            get {
                return this.ManufacturerIDField;
            }
            set {
                if ((this.ManufacturerIDField.Equals(value) != true)) {
                    this.ManufacturerIDField = value;
                    this.RaisePropertyChanged("ManufacturerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Review", Namespace="http://schemas.datacontract.org/2004/07/CPT.WebAPI.Contract.Data")]
    [System.SerializableAttribute()]
    public partial class Review : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacebookIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductRatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductReviewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ReviewIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacebookID {
            get {
                return this.FacebookIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FacebookIDField, value) != true)) {
                    this.FacebookIDField = value;
                    this.RaisePropertyChanged("FacebookID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductRating {
            get {
                return this.ProductRatingField;
            }
            set {
                if ((this.ProductRatingField.Equals(value) != true)) {
                    this.ProductRatingField = value;
                    this.RaisePropertyChanged("ProductRating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductReview {
            get {
                return this.ProductReviewField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductReviewField, value) != true)) {
                    this.ProductReviewField = value;
                    this.RaisePropertyChanged("ProductReview");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ReviewID {
            get {
                return this.ReviewIDField;
            }
            set {
                if ((this.ReviewIDField.Equals(value) != true)) {
                    this.ReviewIDField = value;
                    this.RaisePropertyChanged("ReviewID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceClient.IPublicService")]
    public interface IPublicService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicService/GetProduct", ReplyAction="http://tempuri.org/IPublicService/GetProductResponse")]
        CPT.WebAPI.Tests.WebServiceClient.Product GetProduct(string barcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicService/GetProducts", ReplyAction="http://tempuri.org/IPublicService/GetProductsResponse")]
        CPT.WebAPI.Tests.WebServiceClient.Product[] GetProducts(string[] barcodes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicService/GetReviews", ReplyAction="http://tempuri.org/IPublicService/GetReviewsResponse")]
        CPT.WebAPI.Tests.WebServiceClient.Review[] GetReviews(string productid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicService/AddReview", ReplyAction="http://tempuri.org/IPublicService/AddReviewResponse")]
        string AddReview(string productid, CPT.WebAPI.Tests.WebServiceClient.Review review);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPublicServiceChannel : CPT.WebAPI.Tests.WebServiceClient.IPublicService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PublicServiceClient : System.ServiceModel.ClientBase<CPT.WebAPI.Tests.WebServiceClient.IPublicService>, CPT.WebAPI.Tests.WebServiceClient.IPublicService {
        
        public PublicServiceClient() {
        }
        
        public PublicServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PublicServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublicServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublicServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CPT.WebAPI.Tests.WebServiceClient.Product GetProduct(string barcode) {
            return base.Channel.GetProduct(barcode);
        }
        
        public CPT.WebAPI.Tests.WebServiceClient.Product[] GetProducts(string[] barcodes) {
            return base.Channel.GetProducts(barcodes);
        }
        
        public CPT.WebAPI.Tests.WebServiceClient.Review[] GetReviews(string productid) {
            return base.Channel.GetReviews(productid);
        }
        
        public string AddReview(string productid, CPT.WebAPI.Tests.WebServiceClient.Review review) {
            return base.Channel.AddReview(productid, review);
        }
    }
}
